"""Add all models

Revision ID: e82a884eae7c
Revises: 
Create Date: 2025-04-21 21:20:44.515927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e82a884eae7c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.alter_column('competition_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_index('idx_applications_user_id')

    with op.batch_alter_table('competitions', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.drop_index('idx_competitions_discipline')
        batch_op.drop_index('idx_competitions_format')
        batch_op.drop_index('idx_competitions_status')

    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.alter_column('competition_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('results_competition_id_team_id_key', type_='unique')
        batch_op.create_unique_constraint('_competition_team_uc', ['competition_id', 'team_id'])

    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.drop_constraint('team_members_team_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('team_members_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'teams', ['team_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=256),
               existing_nullable=False)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.drop_index('idx_users_email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_users_email', ['email'], unique=False)
        batch_op.alter_column('last_name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('first_name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('team_members_user_id_fkey', 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('team_members_team_id_fkey', 'teams', ['team_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.drop_constraint('_competition_team_uc', type_='unique')
        batch_op.create_unique_constraint('results_competition_id_team_id_key', ['competition_id', 'team_id'])
        batch_op.alter_column('competition_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('competitions', schema=None) as batch_op:
        batch_op.create_index('idx_competitions_status', ['status'], unique=False)
        batch_op.create_index('idx_competitions_format', ['format'], unique=False)
        batch_op.create_index('idx_competitions_discipline', ['discipline'], unique=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index('idx_applications_user_id', ['user_id'], unique=False)
        batch_op.alter_column('competition_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
